development:
  adapter: postgresql
  encoding: utf8
  database: hard_reader_development
  pool: 5
  host: localhost
  username: <%= ENV["USER"] %>
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: hard_reader_test
  pool: 5
  host: localhost
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: hard_reader_production
  pool: 5
  username: 
  password:
